# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b8d4f83c2be6d6ee7802e003fdd4fc87bf303a752cd32f51930e1c41708fdf95afb98b28f56f6ebd8bd8e6f4add76050525e962f83f58cb0670e31915aa8770

test:
  secret_key_base: 450f18a415665207f324a524f7470072c46fae50e360a6d6d4055bbcd48551ef6053a3d29dc58e8a3b4d0f32c16becab01ee0ff6811bc5af113d9eb6cf59a88e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
